version: "3.3"
services:
    glpi-mariadb:
        image: fametec/glpi:9.5.6-mariadb
        restart: unless-stopped
        volumes: 
          - glpi-mariadb-volume:/var/lib/mysql:rw
        environment: 
          MYSQL_DATABASE: glpi
          MYSQL_USER: "${DATABASE_USER}"
          MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
          MYSQL_RANDOM_ROOT_PASSWORD: 1 
        ports: 
          - 3306:3306
        networks: 
          - glpi-backend
#
#
    glpi: 
        image: fametec/glpi:9.5.6
        restart: unless-stopped
        volumes: 
          - glpi-volume-files:/var/www/html/files:rw
          - glpi-volume-plugins:/var/www/html/plugins:rw
          - glpi-volume-config:/var/www/html/config:rw
        environment: 
#          GLPI_LANG: en_GB
          MARIADB_HOST: glpi-mariadb
          MARIADB_PORT: 3306
          MARIADB_DATABASE: glpi
          MARIADB_USER: "${DATABASE_USER}"
          MARIADB_PASSWORD: "${DATABASE_PASSWORD}"
          VERSION: "9.5.6"
          PLUGINS: "all"
        depends_on: 
          - glpi-mariadb
        ports: 
          - 80:80
        networks: 
          - glpi-frontend
          - glpi-backend
#
# CRON
#
    crond: 
        image: fametec/glpi:9.5.6-crond
        restart: unless-stopped
        depends_on:
          - glpi-mariadb
        environment: 
          MARIADB_HOST: glpi-mariadb
          MARIADB_PORT: 3306
          MARIADB_DATABASE: glpi
          MARIADB_USER: "${DATABASE_USER}"
          MARIADB_PASSWORD: "${DATABASE_PASSWORD}"
        volumes: 
          - glpi-volume-files:/var/www/html/files:rw
          - glpi-volume-plugins:/var/www/html/plugins:rw
          - glpi-volume-config:/var/www/html/config:rw
        networks: 
          - glpi-backend

#
# VOLUMES
#
volumes: 
  glpi-volume-files:
  glpi-volume-plugins:
  glpi-volume-config:
  glpi-mariadb-volume:
#
# NETWORKS
#
networks: 
    glpi-frontend: 
    glpi-backend:
